# Generated by Django 2.2 on 2019-05-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyReference', models.CharField(max_length=20)),
                ('createdDate', models.CharField(max_length=20)),
                ('seizedDate', models.DateField()),
                ('seizedTime', models.TimeField()),
                ('description', models.CharField(max_length=20)),
                ('notes', models.TextField()),
                ('locationRecovered', models.CharField(max_length=20)),
                ('recoveredBy', models.CharField(max_length=20)),
                ('images', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=20)),
                ('operation', models.CharField(max_length=20)),
            ],
        ),
    ]
